
# This is a complete configuration to deploy Loki backed by the filesystem.
# The index will be shipped to the storage via tsdb-shipper.

auth_enabled: false

server:
  http_listen_port: 3100
  http_server_read_timeout: 600s
  http_server_write_timeout: 600s

frontend:
    address: 127.0.0.1
    log_queries_longer_than: 5s
    compress_responses: true
    
common:
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: /tmp/loki

schema_config:
  configs:
  - from: 2020-05-15
    store: tsdb
    object_store: filesystem
    schema: v13
    index:
      prefix: index_
      period: 24h

storage_config:
  filesystem:
    directory: /tmp/loki/chunks
# auth_enabled: false

# server:
  # http_listen_port: 3100

# common:
  # path_prefix: F:\Loki\Loki
  # storage:
    # filesystem:
      # chunks_directory: /loki/chunks
      # rules_directory: /loki/rules
  # replication_factor: 1
  # ring:
    # kvstore:
      # store: inmemory
      
# ingester:
  # lifecycler:
    # address: 127.0.0.1
    # ring:
      # kvstore:
        # store: inmemory
      # replication_factor: 1
    # final_sleep: 0s
  # chunk_idle_period: 5m
  # chunk_retain_period: 30s
  # # max_transfer_retries: 0

# schema_config:
  # configs:
    # - from: "2023-01-05" # <---- A date in the future
      # index:
        # period: 24h
        # prefix: index_
      # object_store: filesystem
      # schema: v13
      # store: tsdb

# storage_config:
  # tsdb_shipper:
    # active_index_directory: /data/tsdb-index
    # cache_location: /data/tsdb-cache
  # # boltdb:
    # # directory: F:\Loki\Loki\boltdb

  # filesystem:
    # directory: /chunks

# limits_config:
  # # enforce_metric_name: false
  # reject_old_samples: true
  # reject_old_samples_max_age: 168h

# # chunk_store_config:
  # # max_look_back_period: 0s

# table_manager:
  # retention_deletes_enabled: false
  # retention_period: 0s
