auth_enabled: false

server:
  http_listen_port: 3100
  grpc_server_max_recv_msg_size: 20000000

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

storage_config:
  named_stores:
    aws:
      minio:
        s3: http://xxxxxxxxxx:xxxxxxxxxxxxxx@192.168.1.154:9000/loki
        s3forcepathstyle: true
      obs:
        s3forcepathstyle: true
        bucketnames: loki-log-chunks
        endpoint: https://obs.north-4.xxx.com
        access_key_id: xxxxxxx
        secret_access_key: xxxxxxxxxxxxxxxxxxxx

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v12
      index:
        prefix: index_
        period: 24h
    - from: 2024-02-28
      store: tsdb
      object_store: minio
      schema: v12
      index:
        prefix: index_
        period: 24h

chunk_store_config:
  chunk_cache_config:
    redis:
      endpoint: "127.0.0.1:6379"
      db: 2
      idle_timeout: 30
      expiration: 1h

ruler:
  alertmanager_url: http://localhost:9093

limits_config:
  allow_structured_metadata: true
  ingestion_rate_mb: 32
  ingestion_burst_size_mb: 64
  max_global_streams_per_user: 0
  reject_old_samples: true
  reject_old_samples_max_age: 24h
  #max_query_lookback: 336h
  retention_period: 336h
  max_query_series: 2000

query_scheduler:
  max_outstanding_requests_per_tenant: 10000

compactor:
  working_directory: /loki/retention
  shared_store: filesystem
  retention_enabled: true

table_manager:
  retention_deletes_enabled: true
  retention_period: 336h